services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bigraidencom-backend
    ports:
      - "5020:3000"
    restart: unless-stopped
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bigraidencom-frontend
    ports:
      - "5021:4000"
    depends_on:
      - backend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
