version: '3.8'

services:
  app:
    image: node:22
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    command: sh -c "npm install && npm run serve"
